Make fix
l3af-project/eBPF-Package-Repository pull request #89
Opened 2024-07-09 08:24 UTC by Atul-source

In this PR I have added creation of vmlinux.h  for individual programs and removed creation in common folder, so that program can build without need of l3af-arch/dev_environment .

issue : #90

2024-07-09 09:41 UTC, sanfern requested changes

2024-07-09 09:41 UTC, sanfern commented on ipfix-flow-exporter/bpf_ipfix_egress.bpf.c
> +#include "./vmlinux.h"
IMHO 
```suggestion
#include "vmlinux.h"
```
add flag "-I." in compiler

2024-07-09 09:41 UTC, sanfern commented on ratelimiting/ratelimiting.bpf.c
> +#include "./vmlinux.h"
```suggestion
#include "vmlinux.h"
```

2024-07-09 09:41 UTC, sanfern commented on tc-root/tc_root_common.h
> +#include "./vmlinux.h"
```suggestion
#include "vmlinux.h"
```

2024-07-09 09:41 UTC, sanfern commented on traffic-mirroring/mirroring_egress.bpf.c
> +#include "./vmlinux.h"
```suggestion
#include "vmlinux.h"
```

2024-07-09 09:41 UTC, sanfern commented on traffic-mirroring/mirroring_ingress.bpf.c
> +#include "./vmlinux.h"
```suggestion
#include "vmlinux.h"
```

2024-07-09 14:24 UTC, sanfern approved these changes
LGTM

2024-07-15 10:25 UTC, aka320 approved these changes
LGTM

2024-07-15 18:44 UTC, merged